### ISSUE TITLE
Rewrite this in Swift instead of middleman

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#2]

**Comment by nofelmahmood** [comment]
Can u kindly elaborate ?

**Comment by kiliankoe** [comment]
The idea is probably to utilize a schwifty static site generator once one emerges instead of middleman, 'cause awesome 😃

**Comment by chriseidhof** [comment]
Yeah I was even thinking of writing one myself.

**Comment by chriseidhof** [comment]
It'd be nice. But it's not really high priority right now, so closing this.
