### ISSUE TITLE
Set up automated deployments

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#23]
We already build using middleman. We should set up automated deployments so that travis pushes to github. To do this, we probably need to take these steps: http://jahed.io/blog/2015/05/31/automating-deployments-to-github-pages-with-middleman-and-travis-ci/

Also, we'll somehow need to run the linter to make sure all speakers are in the data/speakers.yml, and check that there's an entry for each event in data/events.yml. That way, we can merge pull requests straight from github while making sure that everything is correct.

**Comment by chriseidhof** [comment]
Partly, this is working already. Travis should now check if a PR can be built.

**Comment by chriseidhof** [comment]
Actually, this would be better probably: https://gist.github.com/kazu69/11389772

**Comment by orta** [comment]
Would recommend using the CP guides setup, it's also middleman, and it's battle proven ( we've had github token leaks with the deps before ) - you should use my fork of [middleman-ch-pages](https://github.com/orta/middleman-gh-pages) and setup up [travis](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/.travis.yml) ( you should use `rake publish` directly, unless you have complex runtime pre-requisites ( [like us](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/Rakefile#L33-L39) ) )

**Comment by chriseidhof** [comment]
So the setup is that you have a separate user for pushing to github pages? Which probably only has access to that?

**Comment by orta** [comment]
Yeah, https://github.com/cocoapodsbot only does that

**Comment by chriseidhof** [comment]
Cool! Will do that.

**Comment by chriseidhof** [comment]
Sorry for all the commit noise everyone. Trying to get this set up.

**Comment by chriseidhof** [comment]
Ok, it's now "working". Can someone with more ruby/travis fu help out with this?

For some reason, in the deploy script, we have to do a `bundle install` again. I don't understand why? Also, there's lots of weird output at the end of the log ("already exists, no checkout"). Not sure what that's about?

There's an example build output log [here](https://travis-ci.org/chriseidhof/pomotv/builds/98287498)

**Comment by orta** [comment]
Interesting, I wonder if it's something with travis's deploy section of the .yml ( this is new to me )

The command to upload [finishes at the push](https://github.com/orta/middleman-gh-pages/blob/master/lib/middleman-gh-pages/tasks/gh-pages.rake#L80) 

<img width="567" alt="screen shot 2015-12-22 at 11 50 52" src="https://cloud.githubusercontent.com/assets/49038/11954692/58311e6c-a8a2-11e5-9d59-f4f0d6c203ff.png">

but then there's a command that comes afterwards `cd -` which I don't know enough about appended after.

The output looks similar to this [git one](http://stackoverflow.com/questions/10508903/cannot-apply-stash-to-working-directory)

**Comment by chriseidhof** [comment]
I'm not sure what's going on here. I've already wasted too much time on Travis in my life, so I'll just leave it for now and hopefully someone can help make this faster in the future. In any case, it's working (just lots of weird output and slow).
