### ISSUE TITLE
Add WWDC videos?

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#25]

**Comment by aalemayhu** [comment]
+1

**Comment by JaviLorbada** [comment]
Tried to add support for this following result, branch: [wwdc](https://github.com/chriseidhof/ios-videos/tree/wwdc)
- Links seem to work fine.
- No idea how to embed WWDC videos 😰
- I find difficult we could get all the twitter reference for speakers.

Any ideas on that guys?

**Comment by chriseidhof** [comment]
I think there are many speakers without twitter. We can add something else, like `website: ""` in the `speakers.yml`. This way, we don't get linter warnings. I'm not sure if it's possible to embed videos, but we could totally make an exception for those and not have them embedded.

**Comment by JaviLorbada** [comment]
@chriseidhof great! Then I'm gonna proceed with WWDC 2015 for now and add all the video references within #38, after I will add all the speakers trying to find them on Twitter otherwise use `website:""` 👍

**Comment by BalestraPatrick** [comment]
As we did with the talks that have slides, we could add the external link in the `direct-link` entry.

**Comment by chriseidhof** [comment]
I think that's a good idea.
