### ISSUE TITLE
Add tags?

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#36]
How can we encourage adding tags to videos? This would be super helpful. E.g. all videos with "auto layout", or only Swift videos. Any ideas?

**Comment by shams-ahmed** [comment]
- Could start of with creating a list of tags which everyone can follow through.
- add a new section on readme, with a format of listing video

**Comment by jk** [comment]
Tags would be super useful. Perhaps authenticated (?) users could add tags. Popular tags will bubble to the top. But I'm not yet clear how the mechanism should look like when a users wants to search by tags.

**Comment by chriseidhof** [comment]
I pushed a first version. What do you think?

**Comment by shams-ahmed** [comment]
@chriseidhof quite a big step forward, tags are looking good but i think the list will get very big in the future How would section sound i.e UI, Architecture, Network?

**Comment by chriseidhof** [comment]
Absolutely! I think that's a great idea. Let's see what kind of tags people start adding. In the best possible world, we'd have transcripts, so that we can do full text search. But let's see what happens before this gets out of hand.

**Comment by eelco** [comment]
I think tags can be improved (e.g., by adding a better tags page), but I think this issue can be closed?

**Comment by chriseidhof** [comment]
Absolutely!
