### ISSUE TITLE
Add some kind of search (using the video's tags?)

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#4]

**Comment by eelco** [comment]
What are the options here?

Some ideas:
- Something custom. The (future) API (#11) could expose some kind of searchable index.
- [Tipue Search](http://www.tipue.com/search/), similar to custom, but with a large part of the work already done.
- [swiftype](https://swiftype.com), used by [middlemanapp.com](https://middlemanapp.com), also has a free tier
- [Google Custom Search Engine](https://cse.google.com/cse/), will show ads (or costs money)
- No search, just let the search engines index it :trollface:
- … I problably missed some other options.

A paid option does not have to be a problem, e.g. it could be sponsored.

**Comment by eelco** [comment]
Another one:
- [lunr.js](http://lunrjs.com) Looks pretty nice, can also be integrated with Middleman using one of
  - [middleman-search](https://github.com/manastech/middleman-search) (relatively new, but seems the most mature)
  - [middleman-lunr](https://github.com/256dpi/middleman-lunr)
  - [middleman-lunrjs](https://github.com/jnovos/middleman-lunrjs)

**Comment by eelco** [comment]
@chriseidhof If you include something like ‘Closes #4’ in the commit message when merging it will automatically close the issue and link to the merge commit.
