### ISSUE TITLE
Rename to pomo.tv?

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#42]
It's a suggestion by @eelco . He proposed the name pomo.tv. Pomo means apple in Esperanto. This is a much better name than "uiko.de". Does this mean anything weird?

**Comment by eelco** [comment]
I like it! ;)

**Comment by BalestraPatrick** [comment]
Sounds good! :green_apple:.:tv:

**Comment by chriseidhof** [comment]
It's done!
