### ISSUE TITLE
Conferences vs Meetups

### ISSUE THREAD

**Issue by johankj** [chriseidhof/pomotv#54]
Currently we have a lot of talks given at conferences, but some local meetups also record those videos and publishes them online. (See NSLondon, Seattle Xcoders, Brooklyn Swift Developers Meetup, SF Swift Language User Group)
- Should we have a special tag for the events? (E.g. `type: Conference` and `type: Meetup`)
- How should meetups be placed in the `events.yaml`-file? (As it’s currently sorted by date, which doesn’t really apply to meetups)
- Should videos from a meetup be tagged with a date? (Or perhaps all videos should be tagged with a date?)

**Comment by JaviLorbada** [comment]
A special tag to diff between the two of them is a great idea, in the same philosophy, maybe we can categorise the "Events" page using the tag type? (Just `Conference` and `Meetup`)

Then dates for conferences make sense, but I think meetups do not need dates, sorting videos as most recent would be ideal for this.

**Comment by johankj** [comment]
> Then dates for conferences make sense, but I think meetups do not need dates, sorting videos as most recent would be ideal for this.

I was thinking that it would be nice to now if a video from a meetup was recorded/released recently or if it was a few years old.
Dates for conference-videos can be inferred from the date of the conference, but this is not the case with meetup-videos. As such I would suggest adding a date to videos from meetups.

**Comment by shams-ahmed** [comment]
including meetups are nice idea, to keep it simple could do month and year only

**Comment by eelco** [comment]
Not to hijack the issue, but adding dates to the videos (when it was published?) would be very useful for sorting, making sure the atom feeds are stable (currently they update on each build) and being able to filter search results (in the future).

**Comment by chriseidhof** [comment]
I'm all for this! The more metadata we have, the better. Also, adding meetups is a great idea.

With regard to the date: we could even have two: when was this talk given, and when was the video published? The first one is more important (in case there's a long time between the two events).

**Comment by chriseidhof** [comment]
Also, with regard to the .yml file, we could still order them by date?

**Comment by johankj** [comment]
> With regard to the date: we could even have two: when was this talk given, and when was the video published? The first one is more important (in case there's a long time between the two events).

I am all for it. Do we want some kind of official date format so it can be parsed?

> Also, with regard to the .yml file, we could still order them by date?

The videos for meetups can be sorted by recorded-date or published-date and it’s also possible to a 
certain degree for conferences, but how about the ordering of the events? Meetups are ongoing events and as such could be placed both before and after any conference.

**Comment by eelco** [comment]
> Do we want some kind of official date format so it can be parsed?

http://yaml.org/type/timestamp.html

There might be yet another date (although it could be figured out with `git blame`, which is a bad idea): the date the video was added to pomo.tv.

I think we could add another ‘level’ to events: for example a ‘WWDC’ parent-event that contains all WWDCs. Similar for the meetups: ‘CocoaHeadsNL’ can contain for example ‘CocoaHeadsNL December 2015’. I think ‘event’ is a good name for something that happens over a short stretch of time (a conference or a meetup). What would be a good name for the ‘concept’ of such an event?

**Comment by chriseidhof** [comment]
Yes, I think a standardised date format is great. We do have multi-day events, currently. Also, the extra level is a good idea. I'm not sure what's a good name for this. We could also have "event" and "edition". Then the CocoaHeads can have a "December 2015" edition, and WWDC can have a "2016 edition".

**Comment by chriseidhof** [comment]
How do you feel about "event" and "edition"? CocoaHeads Stockholm would be the event, and they would have a "November 2015" edition. Does that work?

**Comment by shams-ahmed** [comment]
@chriseidhof the above approach works but how would you go about searching? especially if timestamp seem like the there preferred choice

**Comment by chriseidhof** [comment]
@shams-ahmed I'm not sure what you mean? Seems like this doesn't influence search too much.

**Comment by shams-ahmed** [comment]
@chriseidhof cool i must of misunderstand..

**Comment by eelco** [comment]
“Edition” sounds good to me! 

A page for an event with multiple editions could look just like the current events page, but with just all the editions of that specific event maybe?

The current Events page lists everything in reverse chronological order. It would be nice to keep it that way, but that would require either some redundancy (and room for error) in structuring the data or a piece of information that could help with the sorting. Any ideas?

**Comment by chriseidhof** [comment]
I think the events page we currently have could actually be the editions page. So what we call events now, we would rather call "editions". They can then be grouped into events (if possible). As a second step, we could create an event page (e.g. a page for CocoaHeads Stockholm or for WWDC).
