### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#55]
I talked a bit about it with @floriankugler, and we can sponsor some money for a new design from objc.io. I'll get in touch with some designers I know to see if they're interested.

**Comment by orta** [comment]
:+1:

**Comment by eelco** [comment]
\o/

**Comment by bontoJR** [comment]
Awesome :+1:

**Comment by johankj** [comment]
Yay :+1:

**Comment by chriseidhof** [comment]
Ping @paulozoom, who will make the new design!
