### ISSUE TITLE
[search] Limits/paging to prevent building huge search result pages

### ISSUE THREAD

**Issue by chriseidhof** [chriseidhof/pomotv#56]

**Comment by eelco** [comment]
I wrote this initially in #51, but I no longer think this is a problem. Even if you make a list of all current videos, it’s not that heavy. Plus, all the information was already loaded when the search index was loaded. If we have 10x the videos or do something else to the search results (that would cause extra requests/loading of data), limiting it might make sense. Personally I like being able to do a ‘subsearch’ by using find in page without having to page.
