### ISSUE TITLE
User video queue

### ISSUE THREAD

**Issue by iainsmith** [chriseidhof/pomotv#60]
Hey Chris, really happy to see this project coming together. 

I'd love to be able to queue up a series of videos and track what I've watched. Ideally this would work across devices & could use GitHub login. 

This would probably require adding a server component and would potentially open up options for other features in the future. E.g push notifications, easy submission of new videos via forms, etc. 

This could be implemented with Parse.com, iCloud, AWS etc, but may incur costs in the future. 

Alternatively if we only expose this feature through GitHub then we could create a pomo_playlist repo in the user'a account. This nicely sidesteps adding a central service for now, but doesn't create the infrastructure for other features down the road. 

Obviously there are down sides beyond just cost, it would complicate development & maintenance. 

What are your thoughts on the feature & infrastructure?

**Comment by chriseidhof** [comment]
This would be really great! I think it could be done completely independently from the current setup. It'd be nice to have a small server for this. For this, we'd probably need some unique identifier for each video.  (See also #58). 

I've always wanted to use something like Amazon Cognito. Maybe that could be a backend? (Not sure, have never used it)

**Comment by iainsmith** [comment]
Cognito is a possibility. I was personally leaning towards Parse.com http://parse.com/ due to previous good experiences with it and their Apple TV SDK announcment. I’ll try and take a look over the holiday period. 

If anyone else is motivated to make a start on this, please do, as I don’t know how much time I’m going to have.

**Comment by chriseidhof** [comment]
I'm a bit afraid of Parse, but feel free to go ahead as you please!

**Comment by eelco** [comment]
FWIW, Amazon Cognito supports Twitter/Digits as an Identity Provider which also supports tvOS (Not GitHub though).

It would be nice to also hook up events from the embedded players ([Vimeo](https://developer.vimeo.com/player/js-api#events), [YouTube](https://developers.google.com/youtube/iframe_api_reference?hl=en#Playback_status) plus a manual way to mark videos as watched/unwatched.

**Comment by chriseidhof** [comment]
I'm closing this for now, I think it'd be a great feature but let's discuss more when there's actually code.
