### ISSUE TITLE
pomocast - convert video -> audio

### ISSUE THREAD

**Issue by orta** [chriseidhof/pomotv#65]
Would be nice to be able to subscribe to this in the form of a podcast.

**Comment by chriseidhof** [comment]
That would be awesome but I don't think there's any way to do this in a good way, copyright-wise. Unless we have very specific permission from conferences to do it.

However.... maybe there's a way to do this in the iOS app. @tomlokhorst? We could maybe even set the video's thumbnail as the cover art (once every few seconds). This way you can even "watch" the slides while the phone is unlocked.

**Comment by tomlokhorst** [comment]
You can certainly listen to a video in the iOS app. Start playing a video, click Home this pauses the video, then click play in Control Center continue playing in the background. Or on an iPad the video can be played with Picture in Picture.

However this all requires a constant high-speed network connection to stream video. A main benefit of real podcasts is that they are small audio files that can be downloaded for offline use. That is not possible with the app.

There are some of websites where you can download youtube videos (or audio versions). Sites like http://pwnyoutube.com. I would hesitate to build something like that in the app, precisely for the reasons for copyright. It would be better to ask conferences to provide downloadable audio versions, although that might be a lot to ask for.

**Comment by chriseidhof** [comment]
We can reach out to conferences, and ask them if we can make their content available as audio. Some might actually be okay with that (they only want the news about their conference to spread, anyway). 

With regard to downloading: what if we call it caching? So you can make a video available offline? I wouldn't be hesitant about that on iOS personally. We could even ship the app outside of the store, that makes it even easier!

**Comment by eelco** [comment]
From [YouTube’s TOS](https://www.youtube.com/t/terms):

> You agree not to use or launch any automated system, including without limitation, "robots," "spiders," or "**offline readers**," that accesses the Service in a manner that sends more request messages to the YouTube servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding the foregoing, YouTube grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, **but not caches or archives of such materials**.

(Emphasis mine)

**Comment by chriseidhof** [comment]
Okay, closing this for now. If someone wants to do this, feel free to open it again, but it looks to me like this is a "nice to have" feature that we cannot really provide.
