### ISSUE TITLE
NSLondon Videos

### ISSUE THREAD

**Issue by jcampbell05** [chriseidhof/pomotv#75]
Just a friendly note that I or someone should add these when the time perchance comes.

**Comment by eelco** [comment]
Do you have a link to the videos?

**Comment by shams-ahmed** [comment]
@eelco i help out at NSLondon, will submit a PR very soon

**Comment by johankj** [comment]
I already have a bunch of the videos on the content-nslondon branch.
Will update it to the events/edition format one of the next days and merge it in.

**Comment by shams-ahmed** [comment]
@johankj November video are up:
https://vimeo.com/channels/nslondon/151043021
https://vimeo.com/channels/nslondon/151043020
