### ISSUE TITLE
Realm.io Videos

### ISSUE THREAD

**Issue by jcampbell05** [chriseidhof/pomotv#76]
Just a friendly not that I or someone should add these when the time perchance comes.

**Comment by eelco** [comment]
The [AltConf 2015 videos](http://www.pomo.tv/events/altconf/2015/) and Swift Summit [London](http://www.pomo.tv/events/swift-summit/london-2015/) and [San Francisco](http://www.pomo.tv/events/swift-summit/san-francisco-2015/) are already added. Any other that you’re missing?

**Comment by chriseidhof** [comment]
Anything else that's missing? Otherwise I'll close this =)

**Comment by dtweston** [comment]
I assume @jcampbell05 is referring to the videos from the presentations from the Swift Language User Group meetings, e.g. https://realm.io/news/benji-encz-unidirectional-data-flow-swift/

**Comment by jcampbell05** [comment]
@dtweston Yeah I think a couple of those aren't on.

**Comment by chriseidhof** [comment]
Would you mind making a pull request, @jcampbell05 ? Closing this one for now.
