### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by tomlokhorst** [chriseidhof/pomotv#93]
I've setup a twitter account [@pomo_tv](https://twitter.com/pomo_tv) that automatically tweets about new videos. This uses [twitterfeed](http://twitterfeed.com), which I've also used for years for [@Hackage](https://twitter.com/Hackage).

The way this is setup, twitterfeed automatically reads http://www.pomo.tv/recent.xml every half hour and tweets the five newest posts it finds.

I don't like the formatting of the tweets as they are now, this needs some cleanup. Currently it looks like this:

> Swift C Interoperability:
>    Tags:
>      swift
>      c
>      interoperability
> 
>   Description:In this talk, ... http://bit.ly/1WraBQp 

Ideally, a tweet should look something like:

> Swift C Interoperability - by @chriseidhof
> In this talk, we'll look at Swift's interoperability with C... http://bit.ly/1WraBQp 

This can be done by either changing the text in the current recent.xml or creating a new twitterfeed.xml.

Thoughts?

**Comment by chriseidhof** [comment]
Awesome! Let's create a second feed :)

**Comment by tomlokhorst** [comment]
Great, I'll create a pull request for a twitterfeed.xml.

**Comment by chriseidhof** [comment]
I've merged the pull request. We could also link to the twitter account from the front page?

**Comment by tomlokhorst** [comment]
I've updated the crawler to point to the live http://www.pomo.tv/twitterfeed.xml. In theory it should work, now we'll have to wait until someone gives a new talk that gets added to the site, to see if it tweets. :-)

**Comment by chriseidhof** [comment]
Awesome! Thanks Tom!
